name: Run Tests unit jest and e2e cypress

on:
  release:
    types: [created]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create .env file from secret
        run: echo "${{ secrets.WEBCUR_FROMT_ENV }}" > .env
      - run: npm ci
      - run: npm run test:unit

  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create .env file from secret
        run: echo "${{ secrets.WEBCUR_FROMT_ENV }}" > .env
      - run: npm ci
      - run: npm run build
      - run: npx serve -s dist -l 8080 &
      - run: npx wait-on http://localhost:8080
      - run: npx cypress run